id: I26B3C34D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:08:27+00:00'
last_modified: '2022-06-07T18:58:39.249479+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ33283
  title: དགོངས་འདུས་འགྲོ་བ་ཀུན་གྲོལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4DB6:
      image_group_id: I1KG16691
      title: ''
      total_pages: 980
      order: 1
      base_file: 4DB6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
