id: P003307
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ33283
  title: དགོངས་འདུས་འགྲོ་བ་ཀུན་གྲོལ།
  author: ''
  volumes:
    dfe0936eee2c44ecab39ef8f52afe7e3:
      image_group_id: I1KG16691
      title: ''
      volume_number: 1
      total_pages: 980
      base_file: v001.txt
